// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_platform_func_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_platform_func_type.proto</summary>
  public static partial class EnumEPlatformFuncTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_platform_func_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEPlatformFuncTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9lbnVtX2VfcGxhdGZvcm1fZnVuY190eXBlLnByb3RvEgZ6cHJvdG8qeAoR",
            "RVBsYXRmb3JtRnVuY1R5cGUSFAoQRUZ1bmNUeXBlRGVmYXVsdBAAEhAKDEVI",
            "ZWFkUHJvZmlsZRABEg8KC0VQaG90b2dyYXBoEAISDwoLRVVuaW9uUGhvdG8Q",
            "AxIZChVFSWRJcFVuaW9uRm9ybWFsUGhvdG8QBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EPlatformFuncType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EPlatformFuncType {
    [pbr::OriginalName("EFuncTypeDefault")] EfuncTypeDefault = 0,
    [pbr::OriginalName("EHeadProfile")] EheadProfile = 1,
    [pbr::OriginalName("EPhotograph")] Ephotograph = 2,
    [pbr::OriginalName("EUnionPhoto")] EunionPhoto = 3,
    [pbr::OriginalName("EIdIpUnionFormalPhoto")] EidIpUnionFormalPhoto = 4,
  }

  #endregion

}

#endregion Designer generated code
