// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_interaction_action_excute_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_interaction_action_excute_type.proto</summary>
  public static partial class EnumEInteractionActionExcuteTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_interaction_action_excute_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEInteractionActionExcuteTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitlbnVtX2VfaW50ZXJhY3Rpb25fYWN0aW9uX2V4Y3V0ZV90eXBlLnByb3Rv",
            "EgZ6cHJvdG8qlAEKHEVJbnRlcmFjdGlvbkFjdGlvbkV4Y3V0ZVR5cGUSJgoi",
            "RUludGVyYWN0aW9uQWN0aW9uRXhjdXRlVHlwZUNsaWVudBAAEiYKIkVJbnRl",
            "cmFjdGlvbkFjdGlvbkV4Y3V0ZVR5cGVTZXJ2ZXIQARIkCiBFSW50ZXJhY3Rp",
            "b25BY3Rpb25FeGN1dGVUeXBlQm90aBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EInteractionActionExcuteType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EInteractionActionExcuteType {
    [pbr::OriginalName("EInteractionActionExcuteTypeClient")] Client = 0,
    [pbr::OriginalName("EInteractionActionExcuteTypeServer")] Server = 1,
    [pbr::OriginalName("EInteractionActionExcuteTypeBoth")] Both = 2,
  }

  #endregion

}

#endregion Designer generated code
