// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_transfer_attr_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_transfer_attr_type.proto</summary>
  public static partial class EnumTransferAttrTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_transfer_attr_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumTransferAttrTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1lbnVtX3RyYW5zZmVyX2F0dHJfdHlwZS5wcm90bxIGenByb3RvKrQBChBU",
            "cmFuc2ZlckF0dHJUeXBlEhgKFFRyYW5zZmVyQXR0clR5cGVOdWxsEAASHwob",
            "VHJhbnNmZXJBdHRyVHlwZUNvbW1vbkxlYXZlEAESHwobVHJhbnNmZXJBdHRy",
            "VHlwZUNvbW1vbkVudGVyEAISIQodVHJhbnNmZXJBdHRyVHlwZVBhc3NMaW5l",
            "TGVhdmUQAxIhCh1UcmFuc2ZlckF0dHJUeXBlUGFzc0xpbmVFbnRlchAEYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.TransferAttrType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TransferAttrType {
    [pbr::OriginalName("TransferAttrTypeNull")] Null = 0,
    [pbr::OriginalName("TransferAttrTypeCommonLeave")] CommonLeave = 1,
    [pbr::OriginalName("TransferAttrTypeCommonEnter")] CommonEnter = 2,
    [pbr::OriginalName("TransferAttrTypePassLineLeave")] PassLineLeave = 3,
    [pbr::OriginalName("TransferAttrTypePassLineEnter")] PassLineEnter = 4,
  }

  #endregion

}

#endregion Designer generated code
