// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_show_item_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_show_item_type.proto</summary>
  public static partial class EnumEShowItemTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_show_item_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEShowItemTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtlbnVtX2Vfc2hvd19pdGVtX3R5cGUucHJvdG8SBnpwcm90byp0Cg1FU2hv",
            "d0l0ZW1UeXBlEhUKEUVTaG93SXRlbVR5cGVOdWxsEAASFwoTRVNob3dJdGVt",
            "VHlwZUNvbW1vbhABEhwKGEVTaG93SXRlbVR5cGVNb250aGx5Q2FyZBACEhUK",
            "EUVTaG93SXRlbVR5cGVUaXBzEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EShowItemType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EShowItemType {
    [pbr::OriginalName("EShowItemTypeNull")] Null = 0,
    [pbr::OriginalName("EShowItemTypeCommon")] Common = 1,
    [pbr::OriginalName("EShowItemTypeMonthlyCard")] MonthlyCard = 2,
    [pbr::OriginalName("EShowItemTypeTips")] Tips = 4,
  }

  #endregion

}

#endregion Designer generated code
