// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_second_damage_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_second_damage_type.proto</summary>
  public static partial class EnumESecondDamageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_second_damage_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumESecondDamageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9lbnVtX2Vfc2Vjb25kX2RhbWFnZV90eXBlLnByb3RvEgZ6cHJvdG8qlAEK",
            "EUVTZWNvbmREYW1hZ2VUeXBlEhoKFkVTZWNvbmREYW1hZ2VUeXBlX0NyaXQQ",
            "ABIbChdFU2Vjb25kRGFtYWdlVHlwZV9CbG9jaxABEiIKHkVTZWNvbmREYW1h",
            "Z2VUeXBlX0F0dGFja2VyTHVjaxACEiIKHkVTZWNvbmREYW1hZ2VUeXBlX0F0",
            "dGFja2VkTHVjaxADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ESecondDamageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ESecondDamageType {
    [pbr::OriginalName("ESecondDamageType_Crit")] Crit = 0,
    [pbr::OriginalName("ESecondDamageType_Block")] Block = 1,
    [pbr::OriginalName("ESecondDamageType_AttackerLuck")] AttackerLuck = 2,
    [pbr::OriginalName("ESecondDamageType_AttackedLuck")] AttackedLuck = 3,
  }

  #endregion

}

#endregion Designer generated code
