// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_activity_reward_limit_times.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_activity_reward_limit_times.proto</summary>
  public static partial class StruActivityRewardLimitTimesReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_activity_reward_limit_times.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruActivityRewardLimitTimesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZzdHJ1X2FjdGl2aXR5X3Jld2FyZF9saW1pdF90aW1lcy5wcm90bxIGenBy",
            "b3RvGhdlbnVtX2VfdGltZXJfdHlwZS5wcm90byJkChhBY3Rpdml0eVJld2Fy",
            "ZExpbWl0VGltZXMSJgoKdGltZXNfdHlwZRgBIAEoDjISLnpwcm90by5FVGlt",
            "ZXJUeXBlEg0KBXRpbWVzGAIgASgNEhEKCW1heF90aW1lcxgDIAEoDWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumETimerTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.ActivityRewardLimitTimes), global::Zproto.ActivityRewardLimitTimes.Parser, new[]{ "TimesType", "Times", "MaxTimes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActivityRewardLimitTimes : pb::IMessage<ActivityRewardLimitTimes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActivityRewardLimitTimes> _parser = new pb::MessageParser<ActivityRewardLimitTimes>(() => new ActivityRewardLimitTimes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActivityRewardLimitTimes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruActivityRewardLimitTimesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityRewardLimitTimes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityRewardLimitTimes(ActivityRewardLimitTimes other) : this() {
      timesType_ = other.timesType_;
      times_ = other.times_;
      maxTimes_ = other.maxTimes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityRewardLimitTimes Clone() {
      return new ActivityRewardLimitTimes(this);
    }

    /// <summary>Field number for the "times_type" field.</summary>
    public const int TimesTypeFieldNumber = 1;
    private global::Zproto.ETimerType timesType_ = global::Zproto.ETimerType.TimerTypeNull;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ETimerType TimesType {
      get { return timesType_; }
      set {
        timesType_ = value;
      }
    }

    /// <summary>Field number for the "times" field.</summary>
    public const int TimesFieldNumber = 2;
    private uint times_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Times {
      get { return times_; }
      set {
        times_ = value;
      }
    }

    /// <summary>Field number for the "max_times" field.</summary>
    public const int MaxTimesFieldNumber = 3;
    private uint maxTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxTimes {
      get { return maxTimes_; }
      set {
        maxTimes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActivityRewardLimitTimes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActivityRewardLimitTimes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimesType != other.TimesType) return false;
      if (Times != other.Times) return false;
      if (MaxTimes != other.MaxTimes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimesType != global::Zproto.ETimerType.TimerTypeNull) hash ^= TimesType.GetHashCode();
      if (Times != 0) hash ^= Times.GetHashCode();
      if (MaxTimes != 0) hash ^= MaxTimes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimesType != global::Zproto.ETimerType.TimerTypeNull) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TimesType);
      }
      if (Times != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Times);
      }
      if (MaxTimes != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MaxTimes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimesType != global::Zproto.ETimerType.TimerTypeNull) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TimesType);
      }
      if (Times != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Times);
      }
      if (MaxTimes != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MaxTimes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimesType != global::Zproto.ETimerType.TimerTypeNull) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TimesType);
      }
      if (Times != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Times);
      }
      if (MaxTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxTimes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActivityRewardLimitTimes other) {
      if (other == null) {
        return;
      }
      if (other.TimesType != global::Zproto.ETimerType.TimerTypeNull) {
        TimesType = other.TimesType;
      }
      if (other.Times != 0) {
        Times = other.Times;
      }
      if (other.MaxTimes != 0) {
        MaxTimes = other.MaxTimes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TimesType = (global::Zproto.ETimerType) input.ReadEnum();
            break;
          }
          case 16: {
            Times = input.ReadUInt32();
            break;
          }
          case 24: {
            MaxTimes = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TimesType = (global::Zproto.ETimerType) input.ReadEnum();
            break;
          }
          case 16: {
            Times = input.ReadUInt32();
            break;
          }
          case 24: {
            MaxTimes = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
