// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_homeland_decoration_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_homeland_decoration_info.proto</summary>
  public static partial class StruHomelandDecorationInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_homeland_decoration_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHomelandDecorationInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzdHJ1X2hvbWVsYW5kX2RlY29yYXRpb25faW5mby5wcm90bxIGenByb3Rv",
            "GiJzdHJ1X2hvbWVsYW5kX2xhbXBsaWdodF9pbmZvLnByb3RvGiFzdHJ1X2hv",
            "bWVsYW5kX21hdGVyaWFsX2luZm8ucHJvdG8i7gEKFkhvbWVsYW5kRGVjb3Jh",
            "dGlvbkluZm8SNQoObGFtcGxpZ2h0X2luZm8YASABKAsyHS56cHJvdG8uSG9t",
            "ZWxhbmRMYW1wbGlnaHRJbmZvEkkKDm1hdGVyaWFsX2luZm9zGAIgAygLMjEu",
            "enByb3RvLkhvbWVsYW5kRGVjb3JhdGlvbkluZm8uTWF0ZXJpYWxJbmZvc0Vu",
            "dHJ5GlIKEk1hdGVyaWFsSW5mb3NFbnRyeRILCgNrZXkYASABKAUSKwoFdmFs",
            "dWUYAiABKAsyHC56cHJvdG8uSG9tZWxhbmRNYXRlcmlhbEluZm86AjgBYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruHomelandLamplightInfoReflection.Descriptor, global::Zproto.StruHomelandMaterialInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HomelandDecorationInfo), global::Zproto.HomelandDecorationInfo.Parser, new[]{ "LamplightInfo", "MaterialInfos" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HomelandDecorationInfo : pb::IMessage<HomelandDecorationInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomelandDecorationInfo> _parser = new pb::MessageParser<HomelandDecorationInfo>(() => new HomelandDecorationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomelandDecorationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHomelandDecorationInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandDecorationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandDecorationInfo(HomelandDecorationInfo other) : this() {
      lamplightInfo_ = other.lamplightInfo_ != null ? other.lamplightInfo_.Clone() : null;
      materialInfos_ = other.materialInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandDecorationInfo Clone() {
      return new HomelandDecorationInfo(this);
    }

    /// <summary>Field number for the "lamplight_info" field.</summary>
    public const int LamplightInfoFieldNumber = 1;
    private global::Zproto.HomelandLamplightInfo lamplightInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.HomelandLamplightInfo LamplightInfo {
      get { return lamplightInfo_; }
      set {
        lamplightInfo_ = value;
      }
    }

    /// <summary>Field number for the "material_infos" field.</summary>
    public const int MaterialInfosFieldNumber = 2;
    private static readonly pbc::MapField<int, global::Zproto.HomelandMaterialInfo>.Codec _map_materialInfos_codec
        = new pbc::MapField<int, global::Zproto.HomelandMaterialInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HomelandMaterialInfo.Parser), 18);
    private readonly pbc::MapField<int, global::Zproto.HomelandMaterialInfo> materialInfos_ = new pbc::MapField<int, global::Zproto.HomelandMaterialInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HomelandMaterialInfo> MaterialInfos {
      get { return materialInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomelandDecorationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomelandDecorationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LamplightInfo, other.LamplightInfo)) return false;
      if (!MaterialInfos.Equals(other.MaterialInfos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (lamplightInfo_ != null) hash ^= LamplightInfo.GetHashCode();
      hash ^= MaterialInfos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (lamplightInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LamplightInfo);
      }
      materialInfos_.WriteTo(output, _map_materialInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (lamplightInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LamplightInfo);
      }
      materialInfos_.WriteTo(ref output, _map_materialInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (lamplightInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LamplightInfo);
      }
      size += materialInfos_.CalculateSize(_map_materialInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomelandDecorationInfo other) {
      if (other == null) {
        return;
      }
      if (other.lamplightInfo_ != null) {
        if (lamplightInfo_ == null) {
          LamplightInfo = new global::Zproto.HomelandLamplightInfo();
        }
        LamplightInfo.MergeFrom(other.LamplightInfo);
      }
      materialInfos_.MergeFrom(other.materialInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (lamplightInfo_ == null) {
              LamplightInfo = new global::Zproto.HomelandLamplightInfo();
            }
            input.ReadMessage(LamplightInfo);
            break;
          }
          case 18: {
            materialInfos_.AddEntriesFrom(input, _map_materialInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (lamplightInfo_ == null) {
              LamplightInfo = new global::Zproto.HomelandLamplightInfo();
            }
            input.ReadMessage(LamplightInfo);
            break;
          }
          case 18: {
            materialInfos_.AddEntriesFrom(ref input, _map_materialInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
