// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_compare_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_compare_type.proto</summary>
  public static partial class EnumECompareTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_compare_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumECompareTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChllbnVtX2VfY29tcGFyZV90eXBlLnByb3RvEgZ6cHJvdG8qdQoMRUNvbXBh",
            "cmVUeXBlEgkKBUVOb25lEAASCgoGRUVxdWFsEAESDAoIRVVuZXF1YWwQAhIM",
            "CghFR3JlYXRlchADEhQKEEVHcmVhdGVyQW5kRXF1YWwQBBIJCgVFTGVzcxAF",
            "EhEKDUVMZXNzQW5kRXF1YWwQBmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ECompareType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ECompareType {
    [pbr::OriginalName("ENone")] Enone = 0,
    [pbr::OriginalName("EEqual")] Eequal = 1,
    [pbr::OriginalName("EUnequal")] Eunequal = 2,
    [pbr::OriginalName("EGreater")] Egreater = 3,
    [pbr::OriginalName("EGreaterAndEqual")] EgreaterAndEqual = 4,
    [pbr::OriginalName("ELess")] Eless = 5,
    [pbr::OriginalName("ELessAndEqual")] ElessAndEqual = 6,
  }

  #endregion

}

#endregion Designer generated code
