// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_match_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_match_type.proto</summary>
  public static partial class EnumEMatchTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_match_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEMatchTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdlbnVtX2VfbWF0Y2hfdHlwZS5wcm90bxIGenByb3RvKkwKCkVNYXRjaFR5",
            "cGUSEgoORU1hdGNoVHlwZU51bGwQABISCg5FTWF0Y2hUeXBlVGVhbRABEhYK",
            "EkVNYXRjaFR5cGVBY3Rpdml0eRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EMatchType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EMatchType {
    [pbr::OriginalName("EMatchTypeNull")] Null = 0,
    [pbr::OriginalName("EMatchTypeTeam")] Team = 1,
    [pbr::OriginalName("EMatchTypeActivity")] Activity = 2,
  }

  #endregion

}

#endregion Designer generated code
