// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_timer_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_timer_type.proto</summary>
  public static partial class EnumETimerTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_timer_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumETimerTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdlbnVtX2VfdGltZXJfdHlwZS5wcm90bxIGenByb3RvKogBCgpFVGltZXJU",
            "eXBlEhEKDVRpbWVyVHlwZU51bGwQABITCg9UaW1lclR5cGVfUG9pbnQQARIR",
            "Cg1UaW1lclR5cGVfRGF5EAISEwoPVGltZXJUeXBlX01vbnRoEAMSEgoOVGlt",
            "ZXJUeXBlX1dlZWsQBBIWChJUaW1lclR5cGVfSW50ZXJ2YWwQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ETimerType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ETimerType {
    [pbr::OriginalName("TimerTypeNull")] TimerTypeNull = 0,
    [pbr::OriginalName("TimerType_Point")] TimerTypePoint = 1,
    [pbr::OriginalName("TimerType_Day")] TimerTypeDay = 2,
    [pbr::OriginalName("TimerType_Month")] TimerTypeMonth = 3,
    [pbr::OriginalName("TimerType_Week")] TimerTypeWeek = 4,
    [pbr::OriginalName("TimerType_Interval")] TimerTypeInterval = 5,
  }

  #endregion

}

#endregion Designer generated code
