// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_text_check_reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_text_check_reply.proto</summary>
  public static partial class StruTextCheckReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_text_check_reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTextCheckReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtzdHJ1X3RleHRfY2hlY2tfcmVwbHkucHJvdG8SBnpwcm90bxoXZW51bV9l",
            "X2Vycm9yX2NvZGUucHJvdG8aF3N0cnVfc2Vzc2lvbl9pbmZvLnByb3RvGiFz",
            "dHJ1X3RleHRfY2hlY2tfZGF0YV9yZXN1bHQucHJvdG8ilAEKDlRleHRDaGVj",
            "a1JlcGx5EiQKB3Nlc3Npb24YASABKAsyEy56cHJvdG8uU2Vzc2lvbkluZm8S",
            "NgoRY2hlY2tfZGF0YV9yZXN1bHQYAiABKAsyGy56cHJvdG8uVGV4dENoZWNr",
            "RGF0YVJlc3VsdBIkCghlcnJfY29kZRgDIAEoDjISLnpwcm90by5FRXJyb3JD",
            "b2RlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruSessionInfoReflection.Descriptor, global::Zproto.StruTextCheckDataResultReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TextCheckReply), global::Zproto.TextCheckReply.Parser, new[]{ "Session", "CheckDataResult", "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextCheckReply : pb::IMessage<TextCheckReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextCheckReply> _parser = new pb::MessageParser<TextCheckReply>(() => new TextCheckReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextCheckReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTextCheckReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextCheckReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextCheckReply(TextCheckReply other) : this() {
      session_ = other.session_ != null ? other.session_.Clone() : null;
      checkDataResult_ = other.checkDataResult_ != null ? other.checkDataResult_.Clone() : null;
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextCheckReply Clone() {
      return new TextCheckReply(this);
    }

    /// <summary>Field number for the "session" field.</summary>
    public const int SessionFieldNumber = 1;
    private global::Zproto.SessionInfo session_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.SessionInfo Session {
      get { return session_; }
      set {
        session_ = value;
      }
    }

    /// <summary>Field number for the "check_data_result" field.</summary>
    public const int CheckDataResultFieldNumber = 2;
    private global::Zproto.TextCheckDataResult checkDataResult_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.TextCheckDataResult CheckDataResult {
      get { return checkDataResult_; }
      set {
        checkDataResult_ = value;
      }
    }

    /// <summary>Field number for the "err_code" field.</summary>
    public const int ErrCodeFieldNumber = 3;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextCheckReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextCheckReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Session, other.Session)) return false;
      if (!object.Equals(CheckDataResult, other.CheckDataResult)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (session_ != null) hash ^= Session.GetHashCode();
      if (checkDataResult_ != null) hash ^= CheckDataResult.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (session_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Session);
      }
      if (checkDataResult_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CheckDataResult);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (session_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Session);
      }
      if (checkDataResult_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CheckDataResult);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (session_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Session);
      }
      if (checkDataResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CheckDataResult);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextCheckReply other) {
      if (other == null) {
        return;
      }
      if (other.session_ != null) {
        if (session_ == null) {
          Session = new global::Zproto.SessionInfo();
        }
        Session.MergeFrom(other.Session);
      }
      if (other.checkDataResult_ != null) {
        if (checkDataResult_ == null) {
          CheckDataResult = new global::Zproto.TextCheckDataResult();
        }
        CheckDataResult.MergeFrom(other.CheckDataResult);
      }
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (session_ == null) {
              Session = new global::Zproto.SessionInfo();
            }
            input.ReadMessage(Session);
            break;
          }
          case 18: {
            if (checkDataResult_ == null) {
              CheckDataResult = new global::Zproto.TextCheckDataResult();
            }
            input.ReadMessage(CheckDataResult);
            break;
          }
          case 24: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (session_ == null) {
              Session = new global::Zproto.SessionInfo();
            }
            input.ReadMessage(Session);
            break;
          }
          case 18: {
            if (checkDataResult_ == null) {
              CheckDataResult = new global::Zproto.TextCheckDataResult();
            }
            input.ReadMessage(CheckDataResult);
            break;
          }
          case 24: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
