// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_match_param_context.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_match_param_context.proto</summary>
  public static partial class StruMatchParamContextReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_match_param_context.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruMatchParamContextReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zdHJ1X21hdGNoX3BhcmFtX2NvbnRleHQucHJvdG8SBnpwcm90bxoXZW51",
            "bV9lX21hdGNoX21vZGUucHJvdG8aG2VudW1fZV9tYXRjaF9zdHJhdGVneS5w",
            "cm90bxoZc3RydV9tYXRjaF9rZXlfaW5mby5wcm90bxocc3RydV9tYXRjaF9w",
            "bGF5ZXJfaW5mby5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byLU",
            "AgoRTWF0Y2hQYXJhbUNvbnRleHQSJgoKbWF0Y2hfbW9kZRgBIAEoDjISLnpw",
            "cm90by5FTWF0Y2hNb2RlEhMKC21hdGNoX3Rva2VuGAQgASgJEg8KB3RlYW1f",
            "aWQYBSABKAMSLgoObWF0Y2hfc3RyYXRlZ3kYBiABKA4yFi56cHJvdG8uRU1h",
            "dGNoU3RyYXRlZ3kSMgoUbWF0Y2hfc3RyYXRlZ3lfcGFyYW0YByABKAsyFC5n",
            "b29nbGUucHJvdG9idWYuQW55EiwKDm1hdGNoX2tleV9pbmZvGAggASgLMhQu",
            "enByb3RvLk1hdGNoS2V5SW5mbxIXCg9tYXRjaF9ncmFpbl9rZXkYCSABKAkS",
            "MgoRbWF0Y2hfcGxheWVyX2luZm8YCiABKAsyFy56cHJvdG8uTWF0Y2hQbGF5",
            "ZXJJbmZvEhIKCmR1bmdlb25faWQYCyABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEMatchModeReflection.Descriptor, global::Zproto.EnumEMatchStrategyReflection.Descriptor, global::Zproto.StruMatchKeyInfoReflection.Descriptor, global::Zproto.StruMatchPlayerInfoReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.MatchParamContext), global::Zproto.MatchParamContext.Parser, new[]{ "MatchMode", "MatchToken", "TeamId", "MatchStrategy", "MatchStrategyParam", "MatchKeyInfo", "MatchGrainKey", "MatchPlayerInfo", "DungeonId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MatchParamContext : pb::IMessage<MatchParamContext>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MatchParamContext> _parser = new pb::MessageParser<MatchParamContext>(() => new MatchParamContext());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MatchParamContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruMatchParamContextReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchParamContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchParamContext(MatchParamContext other) : this() {
      matchMode_ = other.matchMode_;
      matchToken_ = other.matchToken_;
      teamId_ = other.teamId_;
      matchStrategy_ = other.matchStrategy_;
      matchStrategyParam_ = other.matchStrategyParam_ != null ? other.matchStrategyParam_.Clone() : null;
      matchKeyInfo_ = other.matchKeyInfo_ != null ? other.matchKeyInfo_.Clone() : null;
      matchGrainKey_ = other.matchGrainKey_;
      matchPlayerInfo_ = other.matchPlayerInfo_ != null ? other.matchPlayerInfo_.Clone() : null;
      dungeonId_ = other.dungeonId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchParamContext Clone() {
      return new MatchParamContext(this);
    }

    /// <summary>Field number for the "match_mode" field.</summary>
    public const int MatchModeFieldNumber = 1;
    private global::Zproto.EMatchMode matchMode_ = global::Zproto.EMatchMode.Single;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EMatchMode MatchMode {
      get { return matchMode_; }
      set {
        matchMode_ = value;
      }
    }

    /// <summary>Field number for the "match_token" field.</summary>
    public const int MatchTokenFieldNumber = 4;
    private string matchToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MatchToken {
      get { return matchToken_; }
      set {
        matchToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "team_id" field.</summary>
    public const int TeamIdFieldNumber = 5;
    private long teamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TeamId {
      get { return teamId_; }
      set {
        teamId_ = value;
      }
    }

    /// <summary>Field number for the "match_strategy" field.</summary>
    public const int MatchStrategyFieldNumber = 6;
    private global::Zproto.EMatchStrategy matchStrategy_ = global::Zproto.EMatchStrategy.Null;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EMatchStrategy MatchStrategy {
      get { return matchStrategy_; }
      set {
        matchStrategy_ = value;
      }
    }

    /// <summary>Field number for the "match_strategy_param" field.</summary>
    public const int MatchStrategyParamFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Any matchStrategyParam_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any MatchStrategyParam {
      get { return matchStrategyParam_; }
      set {
        matchStrategyParam_ = value;
      }
    }

    /// <summary>Field number for the "match_key_info" field.</summary>
    public const int MatchKeyInfoFieldNumber = 8;
    private global::Zproto.MatchKeyInfo matchKeyInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.MatchKeyInfo MatchKeyInfo {
      get { return matchKeyInfo_; }
      set {
        matchKeyInfo_ = value;
      }
    }

    /// <summary>Field number for the "match_grain_key" field.</summary>
    public const int MatchGrainKeyFieldNumber = 9;
    private string matchGrainKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MatchGrainKey {
      get { return matchGrainKey_; }
      set {
        matchGrainKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "match_player_info" field.</summary>
    public const int MatchPlayerInfoFieldNumber = 10;
    private global::Zproto.MatchPlayerInfo matchPlayerInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.MatchPlayerInfo MatchPlayerInfo {
      get { return matchPlayerInfo_; }
      set {
        matchPlayerInfo_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_id" field.</summary>
    public const int DungeonIdFieldNumber = 11;
    private int dungeonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DungeonId {
      get { return dungeonId_; }
      set {
        dungeonId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MatchParamContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MatchParamContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MatchMode != other.MatchMode) return false;
      if (MatchToken != other.MatchToken) return false;
      if (TeamId != other.TeamId) return false;
      if (MatchStrategy != other.MatchStrategy) return false;
      if (!object.Equals(MatchStrategyParam, other.MatchStrategyParam)) return false;
      if (!object.Equals(MatchKeyInfo, other.MatchKeyInfo)) return false;
      if (MatchGrainKey != other.MatchGrainKey) return false;
      if (!object.Equals(MatchPlayerInfo, other.MatchPlayerInfo)) return false;
      if (DungeonId != other.DungeonId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MatchMode != global::Zproto.EMatchMode.Single) hash ^= MatchMode.GetHashCode();
      if (MatchToken.Length != 0) hash ^= MatchToken.GetHashCode();
      if (TeamId != 0L) hash ^= TeamId.GetHashCode();
      if (MatchStrategy != global::Zproto.EMatchStrategy.Null) hash ^= MatchStrategy.GetHashCode();
      if (matchStrategyParam_ != null) hash ^= MatchStrategyParam.GetHashCode();
      if (matchKeyInfo_ != null) hash ^= MatchKeyInfo.GetHashCode();
      if (MatchGrainKey.Length != 0) hash ^= MatchGrainKey.GetHashCode();
      if (matchPlayerInfo_ != null) hash ^= MatchPlayerInfo.GetHashCode();
      if (DungeonId != 0) hash ^= DungeonId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MatchMode != global::Zproto.EMatchMode.Single) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MatchMode);
      }
      if (MatchToken.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MatchToken);
      }
      if (TeamId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(TeamId);
      }
      if (MatchStrategy != global::Zproto.EMatchStrategy.Null) {
        output.WriteRawTag(48);
        output.WriteEnum((int) MatchStrategy);
      }
      if (matchStrategyParam_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MatchStrategyParam);
      }
      if (matchKeyInfo_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(MatchKeyInfo);
      }
      if (MatchGrainKey.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(MatchGrainKey);
      }
      if (matchPlayerInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MatchPlayerInfo);
      }
      if (DungeonId != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(DungeonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MatchMode != global::Zproto.EMatchMode.Single) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MatchMode);
      }
      if (MatchToken.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MatchToken);
      }
      if (TeamId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(TeamId);
      }
      if (MatchStrategy != global::Zproto.EMatchStrategy.Null) {
        output.WriteRawTag(48);
        output.WriteEnum((int) MatchStrategy);
      }
      if (matchStrategyParam_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MatchStrategyParam);
      }
      if (matchKeyInfo_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(MatchKeyInfo);
      }
      if (MatchGrainKey.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(MatchGrainKey);
      }
      if (matchPlayerInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MatchPlayerInfo);
      }
      if (DungeonId != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(DungeonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MatchMode != global::Zproto.EMatchMode.Single) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MatchMode);
      }
      if (MatchToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MatchToken);
      }
      if (TeamId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamId);
      }
      if (MatchStrategy != global::Zproto.EMatchStrategy.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MatchStrategy);
      }
      if (matchStrategyParam_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MatchStrategyParam);
      }
      if (matchKeyInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MatchKeyInfo);
      }
      if (MatchGrainKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MatchGrainKey);
      }
      if (matchPlayerInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MatchPlayerInfo);
      }
      if (DungeonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DungeonId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MatchParamContext other) {
      if (other == null) {
        return;
      }
      if (other.MatchMode != global::Zproto.EMatchMode.Single) {
        MatchMode = other.MatchMode;
      }
      if (other.MatchToken.Length != 0) {
        MatchToken = other.MatchToken;
      }
      if (other.TeamId != 0L) {
        TeamId = other.TeamId;
      }
      if (other.MatchStrategy != global::Zproto.EMatchStrategy.Null) {
        MatchStrategy = other.MatchStrategy;
      }
      if (other.matchStrategyParam_ != null) {
        if (matchStrategyParam_ == null) {
          MatchStrategyParam = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        MatchStrategyParam.MergeFrom(other.MatchStrategyParam);
      }
      if (other.matchKeyInfo_ != null) {
        if (matchKeyInfo_ == null) {
          MatchKeyInfo = new global::Zproto.MatchKeyInfo();
        }
        MatchKeyInfo.MergeFrom(other.MatchKeyInfo);
      }
      if (other.MatchGrainKey.Length != 0) {
        MatchGrainKey = other.MatchGrainKey;
      }
      if (other.matchPlayerInfo_ != null) {
        if (matchPlayerInfo_ == null) {
          MatchPlayerInfo = new global::Zproto.MatchPlayerInfo();
        }
        MatchPlayerInfo.MergeFrom(other.MatchPlayerInfo);
      }
      if (other.DungeonId != 0) {
        DungeonId = other.DungeonId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MatchMode = (global::Zproto.EMatchMode) input.ReadEnum();
            break;
          }
          case 34: {
            MatchToken = input.ReadString();
            break;
          }
          case 40: {
            TeamId = input.ReadInt64();
            break;
          }
          case 48: {
            MatchStrategy = (global::Zproto.EMatchStrategy) input.ReadEnum();
            break;
          }
          case 58: {
            if (matchStrategyParam_ == null) {
              MatchStrategyParam = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(MatchStrategyParam);
            break;
          }
          case 66: {
            if (matchKeyInfo_ == null) {
              MatchKeyInfo = new global::Zproto.MatchKeyInfo();
            }
            input.ReadMessage(MatchKeyInfo);
            break;
          }
          case 74: {
            MatchGrainKey = input.ReadString();
            break;
          }
          case 82: {
            if (matchPlayerInfo_ == null) {
              MatchPlayerInfo = new global::Zproto.MatchPlayerInfo();
            }
            input.ReadMessage(MatchPlayerInfo);
            break;
          }
          case 88: {
            DungeonId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MatchMode = (global::Zproto.EMatchMode) input.ReadEnum();
            break;
          }
          case 34: {
            MatchToken = input.ReadString();
            break;
          }
          case 40: {
            TeamId = input.ReadInt64();
            break;
          }
          case 48: {
            MatchStrategy = (global::Zproto.EMatchStrategy) input.ReadEnum();
            break;
          }
          case 58: {
            if (matchStrategyParam_ == null) {
              MatchStrategyParam = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(MatchStrategyParam);
            break;
          }
          case 66: {
            if (matchKeyInfo_ == null) {
              MatchKeyInfo = new global::Zproto.MatchKeyInfo();
            }
            input.ReadMessage(MatchKeyInfo);
            break;
          }
          case 74: {
            MatchGrainKey = input.ReadString();
            break;
          }
          case 82: {
            if (matchPlayerInfo_ == null) {
              MatchPlayerInfo = new global::Zproto.MatchPlayerInfo();
            }
            input.ReadMessage(MatchPlayerInfo);
            break;
          }
          case 88: {
            DungeonId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
