// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_transfer_param.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_transfer_param.proto</summary>
  public static partial class StruTransferParamReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_transfer_param.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTransferParamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlzdHJ1X3RyYW5zZmVyX3BhcmFtLnByb3RvEgZ6cHJvdG8aH2VudW1fZV91",
            "c2VyX3RyYW5zZmVyX3R5cGUucHJvdG8aGXN0cnVfcG9zaXRpb25fcGFyYW0u",
            "cHJvdG8ipgIKDVRyYW5zZmVyUGFyYW0SEAoIc2NlbmVfaWQYASABKAUSMAoN",
            "dHJhbnNmZXJfdHlwZRgCIAEoDjIZLnpwcm90by5FVXNlclRyYW5zZmVyVHlw",
            "ZRItCg5wb3NpdGlvbl9wYXJhbRgDIAEoCzIVLnpwcm90by5Qb3NpdGlvblBh",
            "cmFtEhMKC2NoYW5nZV9mbGFnGAQgASgDEhgKEGlzX3NlcnZlcl9zd2l0Y2gY",
            "BSABKAgSHgoWdmlzdWFsX2xheWVyX2NvbmZpZ19pZBgGIAEoBRISCgpzY2Vu",
            "ZV9ndWlkGAcgASgJEhQKDGNvbm5lY3RfZ3VpZBgIIAEoCRIWCg5zdWJfc2Nl",
            "bmVfdXVpZBgJIAEoAxIRCglpc19yZXZpdmUYCiABKAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEUserTransferTypeReflection.Descriptor, global::Zproto.StruPositionParamReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TransferParam), global::Zproto.TransferParam.Parser, new[]{ "SceneId", "TransferType", "PositionParam", "ChangeFlag", "IsServerSwitch", "VisualLayerConfigId", "SceneGuid", "ConnectGuid", "SubSceneUuid", "IsRevive" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TransferParam : pb::IMessage<TransferParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransferParam> _parser = new pb::MessageParser<TransferParam>(() => new TransferParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransferParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTransferParamReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferParam(TransferParam other) : this() {
      sceneId_ = other.sceneId_;
      transferType_ = other.transferType_;
      positionParam_ = other.positionParam_ != null ? other.positionParam_.Clone() : null;
      changeFlag_ = other.changeFlag_;
      isServerSwitch_ = other.isServerSwitch_;
      visualLayerConfigId_ = other.visualLayerConfigId_;
      sceneGuid_ = other.sceneGuid_;
      connectGuid_ = other.connectGuid_;
      subSceneUuid_ = other.subSceneUuid_;
      isRevive_ = other.isRevive_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferParam Clone() {
      return new TransferParam(this);
    }

    /// <summary>Field number for the "scene_id" field.</summary>
    public const int SceneIdFieldNumber = 1;
    private int sceneId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneId {
      get { return sceneId_; }
      set {
        sceneId_ = value;
      }
    }

    /// <summary>Field number for the "transfer_type" field.</summary>
    public const int TransferTypeFieldNumber = 2;
    private global::Zproto.EUserTransferType transferType_ = global::Zproto.EUserTransferType.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EUserTransferType TransferType {
      get { return transferType_; }
      set {
        transferType_ = value;
      }
    }

    /// <summary>Field number for the "position_param" field.</summary>
    public const int PositionParamFieldNumber = 3;
    private global::Zproto.PositionParam positionParam_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.PositionParam PositionParam {
      get { return positionParam_; }
      set {
        positionParam_ = value;
      }
    }

    /// <summary>Field number for the "change_flag" field.</summary>
    public const int ChangeFlagFieldNumber = 4;
    private long changeFlag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ChangeFlag {
      get { return changeFlag_; }
      set {
        changeFlag_ = value;
      }
    }

    /// <summary>Field number for the "is_server_switch" field.</summary>
    public const int IsServerSwitchFieldNumber = 5;
    private bool isServerSwitch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsServerSwitch {
      get { return isServerSwitch_; }
      set {
        isServerSwitch_ = value;
      }
    }

    /// <summary>Field number for the "visual_layer_config_id" field.</summary>
    public const int VisualLayerConfigIdFieldNumber = 6;
    private int visualLayerConfigId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VisualLayerConfigId {
      get { return visualLayerConfigId_; }
      set {
        visualLayerConfigId_ = value;
      }
    }

    /// <summary>Field number for the "scene_guid" field.</summary>
    public const int SceneGuidFieldNumber = 7;
    private string sceneGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SceneGuid {
      get { return sceneGuid_; }
      set {
        sceneGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "connect_guid" field.</summary>
    public const int ConnectGuidFieldNumber = 8;
    private string connectGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConnectGuid {
      get { return connectGuid_; }
      set {
        connectGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sub_scene_uuid" field.</summary>
    public const int SubSceneUuidFieldNumber = 9;
    private long subSceneUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SubSceneUuid {
      get { return subSceneUuid_; }
      set {
        subSceneUuid_ = value;
      }
    }

    /// <summary>Field number for the "is_revive" field.</summary>
    public const int IsReviveFieldNumber = 10;
    private bool isRevive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRevive {
      get { return isRevive_; }
      set {
        isRevive_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransferParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransferParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SceneId != other.SceneId) return false;
      if (TransferType != other.TransferType) return false;
      if (!object.Equals(PositionParam, other.PositionParam)) return false;
      if (ChangeFlag != other.ChangeFlag) return false;
      if (IsServerSwitch != other.IsServerSwitch) return false;
      if (VisualLayerConfigId != other.VisualLayerConfigId) return false;
      if (SceneGuid != other.SceneGuid) return false;
      if (ConnectGuid != other.ConnectGuid) return false;
      if (SubSceneUuid != other.SubSceneUuid) return false;
      if (IsRevive != other.IsRevive) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SceneId != 0) hash ^= SceneId.GetHashCode();
      if (TransferType != global::Zproto.EUserTransferType.Default) hash ^= TransferType.GetHashCode();
      if (positionParam_ != null) hash ^= PositionParam.GetHashCode();
      if (ChangeFlag != 0L) hash ^= ChangeFlag.GetHashCode();
      if (IsServerSwitch != false) hash ^= IsServerSwitch.GetHashCode();
      if (VisualLayerConfigId != 0) hash ^= VisualLayerConfigId.GetHashCode();
      if (SceneGuid.Length != 0) hash ^= SceneGuid.GetHashCode();
      if (ConnectGuid.Length != 0) hash ^= ConnectGuid.GetHashCode();
      if (SubSceneUuid != 0L) hash ^= SubSceneUuid.GetHashCode();
      if (IsRevive != false) hash ^= IsRevive.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SceneId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SceneId);
      }
      if (TransferType != global::Zproto.EUserTransferType.Default) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TransferType);
      }
      if (positionParam_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PositionParam);
      }
      if (ChangeFlag != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ChangeFlag);
      }
      if (IsServerSwitch != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsServerSwitch);
      }
      if (VisualLayerConfigId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(VisualLayerConfigId);
      }
      if (SceneGuid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SceneGuid);
      }
      if (ConnectGuid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ConnectGuid);
      }
      if (SubSceneUuid != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(SubSceneUuid);
      }
      if (IsRevive != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsRevive);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SceneId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SceneId);
      }
      if (TransferType != global::Zproto.EUserTransferType.Default) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TransferType);
      }
      if (positionParam_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PositionParam);
      }
      if (ChangeFlag != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ChangeFlag);
      }
      if (IsServerSwitch != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsServerSwitch);
      }
      if (VisualLayerConfigId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(VisualLayerConfigId);
      }
      if (SceneGuid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SceneGuid);
      }
      if (ConnectGuid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ConnectGuid);
      }
      if (SubSceneUuid != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(SubSceneUuid);
      }
      if (IsRevive != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsRevive);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SceneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneId);
      }
      if (TransferType != global::Zproto.EUserTransferType.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TransferType);
      }
      if (positionParam_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PositionParam);
      }
      if (ChangeFlag != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChangeFlag);
      }
      if (IsServerSwitch != false) {
        size += 1 + 1;
      }
      if (VisualLayerConfigId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VisualLayerConfigId);
      }
      if (SceneGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SceneGuid);
      }
      if (ConnectGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConnectGuid);
      }
      if (SubSceneUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SubSceneUuid);
      }
      if (IsRevive != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransferParam other) {
      if (other == null) {
        return;
      }
      if (other.SceneId != 0) {
        SceneId = other.SceneId;
      }
      if (other.TransferType != global::Zproto.EUserTransferType.Default) {
        TransferType = other.TransferType;
      }
      if (other.positionParam_ != null) {
        if (positionParam_ == null) {
          PositionParam = new global::Zproto.PositionParam();
        }
        PositionParam.MergeFrom(other.PositionParam);
      }
      if (other.ChangeFlag != 0L) {
        ChangeFlag = other.ChangeFlag;
      }
      if (other.IsServerSwitch != false) {
        IsServerSwitch = other.IsServerSwitch;
      }
      if (other.VisualLayerConfigId != 0) {
        VisualLayerConfigId = other.VisualLayerConfigId;
      }
      if (other.SceneGuid.Length != 0) {
        SceneGuid = other.SceneGuid;
      }
      if (other.ConnectGuid.Length != 0) {
        ConnectGuid = other.ConnectGuid;
      }
      if (other.SubSceneUuid != 0L) {
        SubSceneUuid = other.SubSceneUuid;
      }
      if (other.IsRevive != false) {
        IsRevive = other.IsRevive;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SceneId = input.ReadInt32();
            break;
          }
          case 16: {
            TransferType = (global::Zproto.EUserTransferType) input.ReadEnum();
            break;
          }
          case 26: {
            if (positionParam_ == null) {
              PositionParam = new global::Zproto.PositionParam();
            }
            input.ReadMessage(PositionParam);
            break;
          }
          case 32: {
            ChangeFlag = input.ReadInt64();
            break;
          }
          case 40: {
            IsServerSwitch = input.ReadBool();
            break;
          }
          case 48: {
            VisualLayerConfigId = input.ReadInt32();
            break;
          }
          case 58: {
            SceneGuid = input.ReadString();
            break;
          }
          case 66: {
            ConnectGuid = input.ReadString();
            break;
          }
          case 72: {
            SubSceneUuid = input.ReadInt64();
            break;
          }
          case 80: {
            IsRevive = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SceneId = input.ReadInt32();
            break;
          }
          case 16: {
            TransferType = (global::Zproto.EUserTransferType) input.ReadEnum();
            break;
          }
          case 26: {
            if (positionParam_ == null) {
              PositionParam = new global::Zproto.PositionParam();
            }
            input.ReadMessage(PositionParam);
            break;
          }
          case 32: {
            ChangeFlag = input.ReadInt64();
            break;
          }
          case 40: {
            IsServerSwitch = input.ReadBool();
            break;
          }
          case 48: {
            VisualLayerConfigId = input.ReadInt32();
            break;
          }
          case 58: {
            SceneGuid = input.ReadString();
            break;
          }
          case 66: {
            ConnectGuid = input.ReadString();
            break;
          }
          case 72: {
            SubSceneUuid = input.ReadInt64();
            break;
          }
          case 80: {
            IsRevive = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
