// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_union_activity_rank_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_union_activity_rank_info.proto</summary>
  public static partial class StruUnionActivityRankInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_union_activity_rank_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruUnionActivityRankInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzdHJ1X3VuaW9uX2FjdGl2aXR5X3JhbmtfaW5mby5wcm90bxIGenByb3Rv",
            "GhZzdHJ1X2F2YXRhcl9pbmZvLnByb3RvIoUBChVVbmlvbkFjdGl2aXR5UmFu",
            "a0luZm8SDwoHY2hhcl9pZBgBIAEoAxIRCgljaGFyX25hbWUYAiABKAkSJwoL",
            "YXZhdGFyX2luZm8YAyABKAsyEi56cHJvdG8uQXZhdGFySW5mbxIQCghyYW5r",
            "X2lkeBgEIAEoBRINCgV2YWx1ZRgFIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruAvatarInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.UnionActivityRankInfo), global::Zproto.UnionActivityRankInfo.Parser, new[]{ "CharId", "CharName", "AvatarInfo", "RankIdx", "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UnionActivityRankInfo : pb::IMessage<UnionActivityRankInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UnionActivityRankInfo> _parser = new pb::MessageParser<UnionActivityRankInfo>(() => new UnionActivityRankInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UnionActivityRankInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruUnionActivityRankInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnionActivityRankInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnionActivityRankInfo(UnionActivityRankInfo other) : this() {
      charId_ = other.charId_;
      charName_ = other.charName_;
      avatarInfo_ = other.avatarInfo_ != null ? other.avatarInfo_.Clone() : null;
      rankIdx_ = other.rankIdx_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnionActivityRankInfo Clone() {
      return new UnionActivityRankInfo(this);
    }

    /// <summary>Field number for the "char_id" field.</summary>
    public const int CharIdFieldNumber = 1;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "char_name" field.</summary>
    public const int CharNameFieldNumber = 2;
    private string charName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_info" field.</summary>
    public const int AvatarInfoFieldNumber = 3;
    private global::Zproto.AvatarInfo avatarInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.AvatarInfo AvatarInfo {
      get { return avatarInfo_; }
      set {
        avatarInfo_ = value;
      }
    }

    /// <summary>Field number for the "rank_idx" field.</summary>
    public const int RankIdxFieldNumber = 4;
    private int rankIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RankIdx {
      get { return rankIdx_; }
      set {
        rankIdx_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 5;
    private int value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UnionActivityRankInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UnionActivityRankInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (CharName != other.CharName) return false;
      if (!object.Equals(AvatarInfo, other.AvatarInfo)) return false;
      if (RankIdx != other.RankIdx) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (CharName.Length != 0) hash ^= CharName.GetHashCode();
      if (avatarInfo_ != null) hash ^= AvatarInfo.GetHashCode();
      if (RankIdx != 0) hash ^= RankIdx.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CharName);
      }
      if (avatarInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AvatarInfo);
      }
      if (RankIdx != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RankIdx);
      }
      if (Value != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CharName);
      }
      if (avatarInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AvatarInfo);
      }
      if (RankIdx != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RankIdx);
      }
      if (Value != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      if (avatarInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarInfo);
      }
      if (RankIdx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankIdx);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UnionActivityRankInfo other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.CharName.Length != 0) {
        CharName = other.CharName;
      }
      if (other.avatarInfo_ != null) {
        if (avatarInfo_ == null) {
          AvatarInfo = new global::Zproto.AvatarInfo();
        }
        AvatarInfo.MergeFrom(other.AvatarInfo);
      }
      if (other.RankIdx != 0) {
        RankIdx = other.RankIdx;
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            CharName = input.ReadString();
            break;
          }
          case 26: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 32: {
            RankIdx = input.ReadInt32();
            break;
          }
          case 40: {
            Value = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            CharName = input.ReadString();
            break;
          }
          case 26: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 32: {
            RankIdx = input.ReadInt32();
            break;
          }
          case 40: {
            Value = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
