// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_treasure.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_treasure.proto</summary>
  public static partial class StruTreasureReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_treasure.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTreasureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzdHJ1X3RyZWFzdXJlLnByb3RvEgZ6cHJvdG8aHHN0cnVfdHJlYXN1cmVf",
            "aXRlbV9yb3cucHJvdG8aFXN0cnVfZGlydHlfbWFzay5wcm90byKDAwoIVHJl",
            "YXN1cmUSKAoEcm93cxgBIAMoCzIaLnpwcm90by5UcmVhc3VyZS5Sb3dzRW50",
            "cnkSNwoMaGlzdG9yeV9yb3dzGAIgAygLMiEuenByb3RvLlRyZWFzdXJlLkhp",
            "c3RvcnlSb3dzRW50cnkSDAoEZmxhZxgDIAEoCBIUCgxyZWZyZXNoX3RpbWUY",
            "BCABKAMSFwoPc2VsZWN0ZWRfcmV3YXJkGAUgAygFEhEKCXNlYXNvbl9pZBgG",
            "IAEoBRIWCg5sYXN0X3NlYXNvbl9pZBgHIAEoBRIZChFsYXN0X3JlZnJlc2hf",
            "dGltZRgIIAEoAxpECglSb3dzRW50cnkSCwoDa2V5GAEgASgFEiYKBXZhbHVl",
            "GAIgASgLMhcuenByb3RvLlRyZWFzdXJlSXRlbVJvdzoCOAEaSwoQSGlzdG9y",
            "eVJvd3NFbnRyeRILCgNrZXkYASABKAUSJgoFdmFsdWUYAiABKAsyFy56cHJv",
            "dG8uVHJlYXN1cmVJdGVtUm93OgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruTreasureItemRowReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.Treasure), global::Zproto.Treasure.Parser, new[]{ "Rows", "HistoryRows", "Flag", "RefreshTime", "SelectedReward", "SeasonId", "LastSeasonId", "LastRefreshTime" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Treasure : pb::IMessage<Treasure>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Treasure> _parser = new pb::MessageParser<Treasure>(() => new Treasure());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Treasure> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTreasureReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Treasure() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Treasure(Treasure other) : this() {
      rows_ = other.rows_.Clone();
      historyRows_ = other.historyRows_.Clone();
      flag_ = other.flag_;
      refreshTime_ = other.refreshTime_;
      selectedReward_ = other.selectedReward_.Clone();
      seasonId_ = other.seasonId_;
      lastSeasonId_ = other.lastSeasonId_;
      lastRefreshTime_ = other.lastRefreshTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Treasure Clone() {
      return new Treasure(this);
    }

    /// <summary>Field number for the "rows" field.</summary>
    public const int RowsFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Zproto.TreasureItemRow>.Codec _map_rows_codec
        = new pbc::MapField<int, global::Zproto.TreasureItemRow>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.TreasureItemRow.Parser), 10);
    private readonly pbc::MapField<int, global::Zproto.TreasureItemRow> rows_ = new pbc::MapField<int, global::Zproto.TreasureItemRow>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.TreasureItemRow> Rows {
      get { return rows_; }
    }

    /// <summary>Field number for the "history_rows" field.</summary>
    public const int HistoryRowsFieldNumber = 2;
    private static readonly pbc::MapField<int, global::Zproto.TreasureItemRow>.Codec _map_historyRows_codec
        = new pbc::MapField<int, global::Zproto.TreasureItemRow>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.TreasureItemRow.Parser), 18);
    private readonly pbc::MapField<int, global::Zproto.TreasureItemRow> historyRows_ = new pbc::MapField<int, global::Zproto.TreasureItemRow>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.TreasureItemRow> HistoryRows {
      get { return historyRows_; }
    }

    /// <summary>Field number for the "flag" field.</summary>
    public const int FlagFieldNumber = 3;
    private bool flag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Flag {
      get { return flag_; }
      set {
        flag_ = value;
      }
    }

    /// <summary>Field number for the "refresh_time" field.</summary>
    public const int RefreshTimeFieldNumber = 4;
    private long refreshTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RefreshTime {
      get { return refreshTime_; }
      set {
        refreshTime_ = value;
      }
    }

    /// <summary>Field number for the "selected_reward" field.</summary>
    public const int SelectedRewardFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_selectedReward_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> selectedReward_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> SelectedReward {
      get { return selectedReward_; }
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 6;
    private int seasonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    /// <summary>Field number for the "last_season_id" field.</summary>
    public const int LastSeasonIdFieldNumber = 7;
    private int lastSeasonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LastSeasonId {
      get { return lastSeasonId_; }
      set {
        lastSeasonId_ = value;
      }
    }

    /// <summary>Field number for the "last_refresh_time" field.</summary>
    public const int LastRefreshTimeFieldNumber = 8;
    private long lastRefreshTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastRefreshTime {
      get { return lastRefreshTime_; }
      set {
        lastRefreshTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Treasure);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Treasure other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Rows.Equals(other.Rows)) return false;
      if (!HistoryRows.Equals(other.HistoryRows)) return false;
      if (Flag != other.Flag) return false;
      if (RefreshTime != other.RefreshTime) return false;
      if(!selectedReward_.Equals(other.selectedReward_)) return false;
      if (SeasonId != other.SeasonId) return false;
      if (LastSeasonId != other.LastSeasonId) return false;
      if (LastRefreshTime != other.LastRefreshTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Rows.GetHashCode();
      hash ^= HistoryRows.GetHashCode();
      if (Flag != false) hash ^= Flag.GetHashCode();
      if (RefreshTime != 0L) hash ^= RefreshTime.GetHashCode();
      hash ^= selectedReward_.GetHashCode();
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      if (LastSeasonId != 0) hash ^= LastSeasonId.GetHashCode();
      if (LastRefreshTime != 0L) hash ^= LastRefreshTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      rows_.WriteTo(output, _map_rows_codec);
      historyRows_.WriteTo(output, _map_historyRows_codec);
      if (Flag != false) {
        output.WriteRawTag(24);
        output.WriteBool(Flag);
      }
      if (RefreshTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RefreshTime);
      }
      selectedReward_.WriteTo(output, _repeated_selectedReward_codec);
      if (SeasonId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonId);
      }
      if (LastSeasonId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(LastSeasonId);
      }
      if (LastRefreshTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(LastRefreshTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      rows_.WriteTo(ref output, _map_rows_codec);
      historyRows_.WriteTo(ref output, _map_historyRows_codec);
      if (Flag != false) {
        output.WriteRawTag(24);
        output.WriteBool(Flag);
      }
      if (RefreshTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RefreshTime);
      }
      selectedReward_.WriteTo(ref output, _repeated_selectedReward_codec);
      if (SeasonId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonId);
      }
      if (LastSeasonId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(LastSeasonId);
      }
      if (LastRefreshTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(LastRefreshTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += rows_.CalculateSize(_map_rows_codec);
      size += historyRows_.CalculateSize(_map_historyRows_codec);
      if (Flag != false) {
        size += 1 + 1;
      }
      if (RefreshTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RefreshTime);
      }
      size += selectedReward_.CalculateSize(_repeated_selectedReward_codec);
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      if (LastSeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastSeasonId);
      }
      if (LastRefreshTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastRefreshTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Treasure other) {
      if (other == null) {
        return;
      }
      rows_.MergeFrom(other.rows_);
      historyRows_.MergeFrom(other.historyRows_);
      if (other.Flag != false) {
        Flag = other.Flag;
      }
      if (other.RefreshTime != 0L) {
        RefreshTime = other.RefreshTime;
      }
      selectedReward_.Add(other.selectedReward_);
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      if (other.LastSeasonId != 0) {
        LastSeasonId = other.LastSeasonId;
      }
      if (other.LastRefreshTime != 0L) {
        LastRefreshTime = other.LastRefreshTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rows_.AddEntriesFrom(input, _map_rows_codec);
            break;
          }
          case 18: {
            historyRows_.AddEntriesFrom(input, _map_historyRows_codec);
            break;
          }
          case 24: {
            Flag = input.ReadBool();
            break;
          }
          case 32: {
            RefreshTime = input.ReadInt64();
            break;
          }
          case 42:
          case 40: {
            selectedReward_.AddEntriesFrom(input, _repeated_selectedReward_codec);
            break;
          }
          case 48: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 56: {
            LastSeasonId = input.ReadInt32();
            break;
          }
          case 64: {
            LastRefreshTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            rows_.AddEntriesFrom(ref input, _map_rows_codec);
            break;
          }
          case 18: {
            historyRows_.AddEntriesFrom(ref input, _map_historyRows_codec);
            break;
          }
          case 24: {
            Flag = input.ReadBool();
            break;
          }
          case 32: {
            RefreshTime = input.ReadInt64();
            break;
          }
          case 42:
          case 40: {
            selectedReward_.AddEntriesFrom(ref input, _repeated_selectedReward_codec);
            break;
          }
          case 48: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 56: {
            LastSeasonId = input.ReadInt32();
            break;
          }
          case 64: {
            LastRefreshTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
