// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_equip_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_equip_info.proto</summary>
  public static partial class StruEquipInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_equip_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruEquipInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVzdHJ1X2VxdWlwX2luZm8ucHJvdG8SBnpwcm90bxoVc3RydV9kaXJ0eV9t",
            "YXNrLnByb3RvInsKCUVxdWlwSW5mbxISCgplcXVpcF9zbG90GAEgASgFEhEK",
            "CWl0ZW1fdXVpZBgCIAEoBBIfChdlcXVpcF9zbG90X3JlZmluZV9sZXZlbBgD",
            "IAEoDRImCh5lcXVpcF9zbG90X3JlZmluZV9mYWlsZWRfY291bnQYBCABKA1i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.EquipInfo), global::Zproto.EquipInfo.Parser, new[]{ "EquipSlot", "ItemUuid", "EquipSlotRefineLevel", "EquipSlotRefineFailedCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EquipInfo : pb::IMessage<EquipInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EquipInfo> _parser = new pb::MessageParser<EquipInfo>(() => new EquipInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EquipInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruEquipInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EquipInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EquipInfo(EquipInfo other) : this() {
      equipSlot_ = other.equipSlot_;
      itemUuid_ = other.itemUuid_;
      equipSlotRefineLevel_ = other.equipSlotRefineLevel_;
      equipSlotRefineFailedCount_ = other.equipSlotRefineFailedCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EquipInfo Clone() {
      return new EquipInfo(this);
    }

    /// <summary>Field number for the "equip_slot" field.</summary>
    public const int EquipSlotFieldNumber = 1;
    private int equipSlot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EquipSlot {
      get { return equipSlot_; }
      set {
        equipSlot_ = value;
      }
    }

    /// <summary>Field number for the "item_uuid" field.</summary>
    public const int ItemUuidFieldNumber = 2;
    private ulong itemUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ItemUuid {
      get { return itemUuid_; }
      set {
        itemUuid_ = value;
      }
    }

    /// <summary>Field number for the "equip_slot_refine_level" field.</summary>
    public const int EquipSlotRefineLevelFieldNumber = 3;
    private uint equipSlotRefineLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EquipSlotRefineLevel {
      get { return equipSlotRefineLevel_; }
      set {
        equipSlotRefineLevel_ = value;
      }
    }

    /// <summary>Field number for the "equip_slot_refine_failed_count" field.</summary>
    public const int EquipSlotRefineFailedCountFieldNumber = 4;
    private uint equipSlotRefineFailedCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EquipSlotRefineFailedCount {
      get { return equipSlotRefineFailedCount_; }
      set {
        equipSlotRefineFailedCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EquipInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EquipInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EquipSlot != other.EquipSlot) return false;
      if (ItemUuid != other.ItemUuid) return false;
      if (EquipSlotRefineLevel != other.EquipSlotRefineLevel) return false;
      if (EquipSlotRefineFailedCount != other.EquipSlotRefineFailedCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EquipSlot != 0) hash ^= EquipSlot.GetHashCode();
      if (ItemUuid != 0UL) hash ^= ItemUuid.GetHashCode();
      if (EquipSlotRefineLevel != 0) hash ^= EquipSlotRefineLevel.GetHashCode();
      if (EquipSlotRefineFailedCount != 0) hash ^= EquipSlotRefineFailedCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EquipSlot != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EquipSlot);
      }
      if (ItemUuid != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ItemUuid);
      }
      if (EquipSlotRefineLevel != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(EquipSlotRefineLevel);
      }
      if (EquipSlotRefineFailedCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EquipSlotRefineFailedCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EquipSlot != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EquipSlot);
      }
      if (ItemUuid != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ItemUuid);
      }
      if (EquipSlotRefineLevel != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(EquipSlotRefineLevel);
      }
      if (EquipSlotRefineFailedCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EquipSlotRefineFailedCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EquipSlot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EquipSlot);
      }
      if (ItemUuid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ItemUuid);
      }
      if (EquipSlotRefineLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EquipSlotRefineLevel);
      }
      if (EquipSlotRefineFailedCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EquipSlotRefineFailedCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EquipInfo other) {
      if (other == null) {
        return;
      }
      if (other.EquipSlot != 0) {
        EquipSlot = other.EquipSlot;
      }
      if (other.ItemUuid != 0UL) {
        ItemUuid = other.ItemUuid;
      }
      if (other.EquipSlotRefineLevel != 0) {
        EquipSlotRefineLevel = other.EquipSlotRefineLevel;
      }
      if (other.EquipSlotRefineFailedCount != 0) {
        EquipSlotRefineFailedCount = other.EquipSlotRefineFailedCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EquipSlot = input.ReadInt32();
            break;
          }
          case 16: {
            ItemUuid = input.ReadUInt64();
            break;
          }
          case 24: {
            EquipSlotRefineLevel = input.ReadUInt32();
            break;
          }
          case 32: {
            EquipSlotRefineFailedCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EquipSlot = input.ReadInt32();
            break;
          }
          case 16: {
            ItemUuid = input.ReadUInt64();
            break;
          }
          case 24: {
            EquipSlotRefineLevel = input.ReadUInt32();
            break;
          }
          case 32: {
            EquipSlotRefineFailedCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
