// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_handbook_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_handbook_data.proto</summary>
  public static partial class StruHandbookDataReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_handbook_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHandbookDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhzdHJ1X2hhbmRib29rX2RhdGEucHJvdG8SBnpwcm90bxobc3RydV9oYW5k",
            "X2Jvb2tfc3RydWN0LnByb3RvGhVzdHJ1X2RpcnR5X21hc2sucHJvdG8igAcK",
            "DEhhbmRib29rRGF0YRJcCh51bmxvY2tfbm90ZV9pbXBvcnRhbnRfcm9sZV9t",
            "YXAYASADKAsyNC56cHJvdG8uSGFuZGJvb2tEYXRhLlVubG9ja05vdGVJbXBv",
            "cnRhbnRSb2xlTWFwRW50cnkSWAocdW5sb2NrX25vdGVfcmVhZGluZ19ib29r",
            "X21hcBgCIAMoCzIyLnpwcm90by5IYW5kYm9va0RhdGEuVW5sb2NrTm90ZVJl",
            "YWRpbmdCb29rTWFwRW50cnkSVQoadW5sb2NrX25vdGVfZGljdGlvbmFyeV9t",
            "YXAYAyADKAsyMS56cHJvdG8uSGFuZGJvb2tEYXRhLlVubG9ja05vdGVEaWN0",
            "aW9uYXJ5TWFwRW50cnkSUgoZdW5sb2NrX25vdGVfcG9zdF9jYXJkX21hcBgE",
            "IAMoCzIvLnpwcm90by5IYW5kYm9va0RhdGEuVW5sb2NrTm90ZVBvc3RDYXJk",
            "TWFwRW50cnkSVAoadW5sb2NrX25vdGVfbW9udGhfY2FyZF9tYXAYBSADKAsy",
            "MC56cHJvdG8uSGFuZGJvb2tEYXRhLlVubG9ja05vdGVNb250aENhcmRNYXBF",
            "bnRyeRpZCh9VbmxvY2tOb3RlSW1wb3J0YW50Um9sZU1hcEVudHJ5EgsKA2tl",
            "eRgBIAEoBRIlCgV2YWx1ZRgCIAEoCzIWLnpwcm90by5IYW5kQm9va1N0cnVj",
            "dDoCOAEaVwodVW5sb2NrTm90ZVJlYWRpbmdCb29rTWFwRW50cnkSCwoDa2V5",
            "GAEgASgFEiUKBXZhbHVlGAIgASgLMhYuenByb3RvLkhhbmRCb29rU3RydWN0",
            "OgI4ARpWChxVbmxvY2tOb3RlRGljdGlvbmFyeU1hcEVudHJ5EgsKA2tleRgB",
            "IAEoBRIlCgV2YWx1ZRgCIAEoCzIWLnpwcm90by5IYW5kQm9va1N0cnVjdDoC",
            "OAEaVAoaVW5sb2NrTm90ZVBvc3RDYXJkTWFwRW50cnkSCwoDa2V5GAEgASgF",
            "EiUKBXZhbHVlGAIgASgLMhYuenByb3RvLkhhbmRCb29rU3RydWN0OgI4ARpV",
            "ChtVbmxvY2tOb3RlTW9udGhDYXJkTWFwRW50cnkSCwoDa2V5GAEgASgFEiUK",
            "BXZhbHVlGAIgASgLMhYuenByb3RvLkhhbmRCb29rU3RydWN0OgI4AWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruHandBookStructReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HandbookData), global::Zproto.HandbookData.Parser, new[]{ "UnlockNoteImportantRoleMap", "UnlockNoteReadingBookMap", "UnlockNoteDictionaryMap", "UnlockNotePostCardMap", "UnlockNoteMonthCardMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HandbookData : pb::IMessage<HandbookData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandbookData> _parser = new pb::MessageParser<HandbookData>(() => new HandbookData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandbookData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHandbookDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandbookData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandbookData(HandbookData other) : this() {
      unlockNoteImportantRoleMap_ = other.unlockNoteImportantRoleMap_.Clone();
      unlockNoteReadingBookMap_ = other.unlockNoteReadingBookMap_.Clone();
      unlockNoteDictionaryMap_ = other.unlockNoteDictionaryMap_.Clone();
      unlockNotePostCardMap_ = other.unlockNotePostCardMap_.Clone();
      unlockNoteMonthCardMap_ = other.unlockNoteMonthCardMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandbookData Clone() {
      return new HandbookData(this);
    }

    /// <summary>Field number for the "unlock_note_important_role_map" field.</summary>
    public const int UnlockNoteImportantRoleMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Zproto.HandBookStruct>.Codec _map_unlockNoteImportantRoleMap_codec
        = new pbc::MapField<int, global::Zproto.HandBookStruct>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HandBookStruct.Parser), 10);
    private readonly pbc::MapField<int, global::Zproto.HandBookStruct> unlockNoteImportantRoleMap_ = new pbc::MapField<int, global::Zproto.HandBookStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HandBookStruct> UnlockNoteImportantRoleMap {
      get { return unlockNoteImportantRoleMap_; }
    }

    /// <summary>Field number for the "unlock_note_reading_book_map" field.</summary>
    public const int UnlockNoteReadingBookMapFieldNumber = 2;
    private static readonly pbc::MapField<int, global::Zproto.HandBookStruct>.Codec _map_unlockNoteReadingBookMap_codec
        = new pbc::MapField<int, global::Zproto.HandBookStruct>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HandBookStruct.Parser), 18);
    private readonly pbc::MapField<int, global::Zproto.HandBookStruct> unlockNoteReadingBookMap_ = new pbc::MapField<int, global::Zproto.HandBookStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HandBookStruct> UnlockNoteReadingBookMap {
      get { return unlockNoteReadingBookMap_; }
    }

    /// <summary>Field number for the "unlock_note_dictionary_map" field.</summary>
    public const int UnlockNoteDictionaryMapFieldNumber = 3;
    private static readonly pbc::MapField<int, global::Zproto.HandBookStruct>.Codec _map_unlockNoteDictionaryMap_codec
        = new pbc::MapField<int, global::Zproto.HandBookStruct>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HandBookStruct.Parser), 26);
    private readonly pbc::MapField<int, global::Zproto.HandBookStruct> unlockNoteDictionaryMap_ = new pbc::MapField<int, global::Zproto.HandBookStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HandBookStruct> UnlockNoteDictionaryMap {
      get { return unlockNoteDictionaryMap_; }
    }

    /// <summary>Field number for the "unlock_note_post_card_map" field.</summary>
    public const int UnlockNotePostCardMapFieldNumber = 4;
    private static readonly pbc::MapField<int, global::Zproto.HandBookStruct>.Codec _map_unlockNotePostCardMap_codec
        = new pbc::MapField<int, global::Zproto.HandBookStruct>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HandBookStruct.Parser), 34);
    private readonly pbc::MapField<int, global::Zproto.HandBookStruct> unlockNotePostCardMap_ = new pbc::MapField<int, global::Zproto.HandBookStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HandBookStruct> UnlockNotePostCardMap {
      get { return unlockNotePostCardMap_; }
    }

    /// <summary>Field number for the "unlock_note_month_card_map" field.</summary>
    public const int UnlockNoteMonthCardMapFieldNumber = 5;
    private static readonly pbc::MapField<int, global::Zproto.HandBookStruct>.Codec _map_unlockNoteMonthCardMap_codec
        = new pbc::MapField<int, global::Zproto.HandBookStruct>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HandBookStruct.Parser), 42);
    private readonly pbc::MapField<int, global::Zproto.HandBookStruct> unlockNoteMonthCardMap_ = new pbc::MapField<int, global::Zproto.HandBookStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HandBookStruct> UnlockNoteMonthCardMap {
      get { return unlockNoteMonthCardMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandbookData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandbookData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!UnlockNoteImportantRoleMap.Equals(other.UnlockNoteImportantRoleMap)) return false;
      if (!UnlockNoteReadingBookMap.Equals(other.UnlockNoteReadingBookMap)) return false;
      if (!UnlockNoteDictionaryMap.Equals(other.UnlockNoteDictionaryMap)) return false;
      if (!UnlockNotePostCardMap.Equals(other.UnlockNotePostCardMap)) return false;
      if (!UnlockNoteMonthCardMap.Equals(other.UnlockNoteMonthCardMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= UnlockNoteImportantRoleMap.GetHashCode();
      hash ^= UnlockNoteReadingBookMap.GetHashCode();
      hash ^= UnlockNoteDictionaryMap.GetHashCode();
      hash ^= UnlockNotePostCardMap.GetHashCode();
      hash ^= UnlockNoteMonthCardMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unlockNoteImportantRoleMap_.WriteTo(output, _map_unlockNoteImportantRoleMap_codec);
      unlockNoteReadingBookMap_.WriteTo(output, _map_unlockNoteReadingBookMap_codec);
      unlockNoteDictionaryMap_.WriteTo(output, _map_unlockNoteDictionaryMap_codec);
      unlockNotePostCardMap_.WriteTo(output, _map_unlockNotePostCardMap_codec);
      unlockNoteMonthCardMap_.WriteTo(output, _map_unlockNoteMonthCardMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unlockNoteImportantRoleMap_.WriteTo(ref output, _map_unlockNoteImportantRoleMap_codec);
      unlockNoteReadingBookMap_.WriteTo(ref output, _map_unlockNoteReadingBookMap_codec);
      unlockNoteDictionaryMap_.WriteTo(ref output, _map_unlockNoteDictionaryMap_codec);
      unlockNotePostCardMap_.WriteTo(ref output, _map_unlockNotePostCardMap_codec);
      unlockNoteMonthCardMap_.WriteTo(ref output, _map_unlockNoteMonthCardMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unlockNoteImportantRoleMap_.CalculateSize(_map_unlockNoteImportantRoleMap_codec);
      size += unlockNoteReadingBookMap_.CalculateSize(_map_unlockNoteReadingBookMap_codec);
      size += unlockNoteDictionaryMap_.CalculateSize(_map_unlockNoteDictionaryMap_codec);
      size += unlockNotePostCardMap_.CalculateSize(_map_unlockNotePostCardMap_codec);
      size += unlockNoteMonthCardMap_.CalculateSize(_map_unlockNoteMonthCardMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandbookData other) {
      if (other == null) {
        return;
      }
      unlockNoteImportantRoleMap_.MergeFrom(other.unlockNoteImportantRoleMap_);
      unlockNoteReadingBookMap_.MergeFrom(other.unlockNoteReadingBookMap_);
      unlockNoteDictionaryMap_.MergeFrom(other.unlockNoteDictionaryMap_);
      unlockNotePostCardMap_.MergeFrom(other.unlockNotePostCardMap_);
      unlockNoteMonthCardMap_.MergeFrom(other.unlockNoteMonthCardMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            unlockNoteImportantRoleMap_.AddEntriesFrom(input, _map_unlockNoteImportantRoleMap_codec);
            break;
          }
          case 18: {
            unlockNoteReadingBookMap_.AddEntriesFrom(input, _map_unlockNoteReadingBookMap_codec);
            break;
          }
          case 26: {
            unlockNoteDictionaryMap_.AddEntriesFrom(input, _map_unlockNoteDictionaryMap_codec);
            break;
          }
          case 34: {
            unlockNotePostCardMap_.AddEntriesFrom(input, _map_unlockNotePostCardMap_codec);
            break;
          }
          case 42: {
            unlockNoteMonthCardMap_.AddEntriesFrom(input, _map_unlockNoteMonthCardMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            unlockNoteImportantRoleMap_.AddEntriesFrom(ref input, _map_unlockNoteImportantRoleMap_codec);
            break;
          }
          case 18: {
            unlockNoteReadingBookMap_.AddEntriesFrom(ref input, _map_unlockNoteReadingBookMap_codec);
            break;
          }
          case 26: {
            unlockNoteDictionaryMap_.AddEntriesFrom(ref input, _map_unlockNoteDictionaryMap_codec);
            break;
          }
          case 34: {
            unlockNotePostCardMap_.AddEntriesFrom(ref input, _map_unlockNotePostCardMap_codec);
            break;
          }
          case 42: {
            unlockNoteMonthCardMap_.AddEntriesFrom(ref input, _map_unlockNoteMonthCardMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
