// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_lif_profession_point_tips_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_lif_profession_point_tips_info.proto</summary>
  public static partial class StruLifProfessionPointTipsInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_lif_profession_point_tips_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruLifProfessionPointTipsInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilzdHJ1X2xpZl9wcm9mZXNzaW9uX3BvaW50X3RpcHNfaW5mby5wcm90bxIG",
            "enByb3RvGh1lbnVtX2VfaXRlbV9nZXRfb3B0X3NyYy5wcm90byKCAQoaTGlm",
            "UHJvZmVzc2lvblBvaW50VGlwc0luZm8SMwoTZ2V0X2xpZmVfcG9pbnRfdHlw",
            "ZRgBIAEoDjIWLnpwcm90by5FSXRlbUdldE9wdFNyYxIaChJsaWZlX3Byb2Zl",
            "c3Npb25faWQYAiABKA0SEwoLcG9pbnRfY291bnQYAyABKA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEItemGetOptSrcReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.LifProfessionPointTipsInfo), global::Zproto.LifProfessionPointTipsInfo.Parser, new[]{ "GetLifePointType", "LifeProfessionId", "PointCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LifProfessionPointTipsInfo : pb::IMessage<LifProfessionPointTipsInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LifProfessionPointTipsInfo> _parser = new pb::MessageParser<LifProfessionPointTipsInfo>(() => new LifProfessionPointTipsInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LifProfessionPointTipsInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruLifProfessionPointTipsInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LifProfessionPointTipsInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LifProfessionPointTipsInfo(LifProfessionPointTipsInfo other) : this() {
      getLifePointType_ = other.getLifePointType_;
      lifeProfessionId_ = other.lifeProfessionId_;
      pointCount_ = other.pointCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LifProfessionPointTipsInfo Clone() {
      return new LifProfessionPointTipsInfo(this);
    }

    /// <summary>Field number for the "get_life_point_type" field.</summary>
    public const int GetLifePointTypeFieldNumber = 1;
    private global::Zproto.EItemGetOptSrc getLifePointType_ = global::Zproto.EItemGetOptSrc.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EItemGetOptSrc GetLifePointType {
      get { return getLifePointType_; }
      set {
        getLifePointType_ = value;
      }
    }

    /// <summary>Field number for the "life_profession_id" field.</summary>
    public const int LifeProfessionIdFieldNumber = 2;
    private uint lifeProfessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LifeProfessionId {
      get { return lifeProfessionId_; }
      set {
        lifeProfessionId_ = value;
      }
    }

    /// <summary>Field number for the "point_count" field.</summary>
    public const int PointCountFieldNumber = 3;
    private uint pointCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PointCount {
      get { return pointCount_; }
      set {
        pointCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LifProfessionPointTipsInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LifProfessionPointTipsInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GetLifePointType != other.GetLifePointType) return false;
      if (LifeProfessionId != other.LifeProfessionId) return false;
      if (PointCount != other.PointCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GetLifePointType != global::Zproto.EItemGetOptSrc.Default) hash ^= GetLifePointType.GetHashCode();
      if (LifeProfessionId != 0) hash ^= LifeProfessionId.GetHashCode();
      if (PointCount != 0) hash ^= PointCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GetLifePointType != global::Zproto.EItemGetOptSrc.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GetLifePointType);
      }
      if (LifeProfessionId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(LifeProfessionId);
      }
      if (PointCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PointCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GetLifePointType != global::Zproto.EItemGetOptSrc.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GetLifePointType);
      }
      if (LifeProfessionId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(LifeProfessionId);
      }
      if (PointCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PointCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GetLifePointType != global::Zproto.EItemGetOptSrc.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GetLifePointType);
      }
      if (LifeProfessionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LifeProfessionId);
      }
      if (PointCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PointCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LifProfessionPointTipsInfo other) {
      if (other == null) {
        return;
      }
      if (other.GetLifePointType != global::Zproto.EItemGetOptSrc.Default) {
        GetLifePointType = other.GetLifePointType;
      }
      if (other.LifeProfessionId != 0) {
        LifeProfessionId = other.LifeProfessionId;
      }
      if (other.PointCount != 0) {
        PointCount = other.PointCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GetLifePointType = (global::Zproto.EItemGetOptSrc) input.ReadEnum();
            break;
          }
          case 16: {
            LifeProfessionId = input.ReadUInt32();
            break;
          }
          case 24: {
            PointCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GetLifePointType = (global::Zproto.EItemGetOptSrc) input.ReadEnum();
            break;
          }
          case 16: {
            LifeProfessionId = input.ReadUInt32();
            break;
          }
          case 24: {
            PointCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
